export const config = {
  data: {
    id: 261,
    created_at: "2019-10-19 15:42:24",
    updated_at: "2022-08-03 18:30:46",
    label: "Web Config",
    description:
      "Manages visual configuration for the brand's web ordering site.",
    module_id: 41,
    data: {
      seo: {
        image:
          "https://koala-marketing-api-sandbox.s3.amazonaws.com/default-assets/header-logo.png",
        title: "Koala Grill",
        base_url: "",
        site_name: "Koala Grill",
        description: "Koala Grill",
        store_page_title: "$productName$ - $label$",
        product_page_title: "$label$, $state$ - Fuzz Grill",
        store_page_description: "$productDescription$ - Available at $label$",
        product_page_description: "Relax at $label$ in $state$",
      },
      menu: {
        background: {
          size: "auto",
          image: null,
          repeat: "none",
          attachment: "scroll",
          vertical_position: "top",
          horizontal_position: "left",
        },
        menu_search: false,
        product_exclusions: [],
        category_exclusions: [],
        mobile_web_product_grid: "1x",
        dietary_preferences_enabled: true,
      },
      text: {
        primary_text_size: 14,
        primary_text_color: "#222222",
        secondary_text_size: 16,
        secondary_text_color: "#222222",
      },
      admin: { food_hall: false },
      forms: {
        font_size: null,
        font_color: null,
        font_family: null,
        border_color: null,
        field_height: 48,
        border_radius: null,
        background_color: "#ffeeeb",
        placeholder_color: "#f22702",
      },
      global: {
        favicon: "/favicon.ico",
        body_color: "#fbf8f7",
        error_color: "#ff0000",
        border_radius: 5,
        success_color: "#008060",
        footer_enabled: true,
        loading_bar_color: "#0d6cf2",
        primary_active_color: "#0d6cf2",
        primary_border_color: "#e1e1e1",
        secondary_body_color: "#fbf8f7",
      },
      google: {
        gtag_id: "G-GGZXW4KW88",
        ecommerce: true,
        analytics_id: "UA-131252767-1",
        tag_manager_id: null,
        site_verification: null,
      },
      header: {
        logo: "https://koala-marketing-api-sandbox.s3.amazonaws.com/fuzz-restaurant-co/assets/koala-logo-black.png",
        cart_icon:
          "https://koala-marketing-api-dev.s3.amazonaws.com/veggie-grill/assets/bag-2.svg",
        font_size: 16,
        font_color: "#222222",
        font_family: '"Arial", "Helvetica"',
        account_icon: null,
        border_color: "#c5c7c8",
        border_radius: 5,
        background_color: "#ffffff",
        background_image: null,
        active_font_color: "#ffffff",
        back_to_menu_icon: null,
        mobile_logo_width: 200,
        desktop_logo_width: 280,
        active_border_color: "#0d6cf2",
        active_background_color: "#0d6cf2",
      },
      modals: {
        font_size: null,
        font_color: null,
        font_family: null,
        border_color: "#f4f5f6",
        footer_color: "#fbf8f7",
        border_radius: null,
        background_color: null,
        active_font_color: null,
        tertiary_font_size: null,
        active_border_color: null,
        secondary_font_size: 24,
        tertiary_font_color: "#0d6cf2",
        secondary_font_color: null,
        tertiary_font_family: '"Arial", "Helvetica"',
        secondary_font_family: '"Arial", "Helvetica"',
        active_background_color: null,
      },
      buttons: {
        primary_button_text_color: "#ffffff",
        knockout_button_text_color: "#0d6cf2",
        primary_button_font_family: '"Arial", "Helvetica"',
        knockout_button_font_family: '"Arial", "Helvetica"',
        primary_button_border_color: "#0d6cf2",
        secondary_button_text_color: "#ffffff",
        knockout_button_border_color: "#0d6cf2",
        primary_button_border_radius: 8,
        secondary_button_font_family: '"Arial", "Helvetica"',
        knockout_button_border_radius: 8,
        secondary_button_border_color: "#70706f",
        secondary_button_border_radius: 8,
        primary_button_background_color: "#0d6cf2",
        primary_button_text_hover_color: "#ffffff",
        knockout_button_background_color: "rgba(255, 255, 255, 0.0)",
        knockout_button_text_hover_color: "#ffffff",
        primary_button_border_hover_color: "#0d6cf2",
        secondary_button_background_color: "#4a4a4a",
        secondary_button_text_hover_color: "#ffffff",
        knockout_button_border_hover_color: "#0d6cf2",
        secondary_button_border_hover_color: "#0d6cf2",
        primary_button_background_hover_color: "#0d6cf2",
        knockout_button_background_hover_color: "#0d6cf2",
        secondary_button_background_hover_color: "#0d6cf2",
      },
      rewards: { footer_heading_text_align: "left" },
      accounts: {
        birthday: "disabled",
        reorders: false,
        zip_code: "disabled",
        barcode_scan: true,
        rewards_icon: null,
        nav_font_size: 16,
        disable_accounts: false,
        stored_addresses: false,
        favorite_location: "disabled",
        opt_in_auto_select: false,
        punchh_referral_code_field: false,
      },
      checkout: {
        font_size: null,
        font_color: null,
        font_family: null,
        border_color: null,
        guest_opt_in: true,
        border_radius: null,
        background_color: null,
        active_font_color: null,
        active_border_color: null,
        cart_image_override: null,
        secondary_font_size: 16,
        show_product_images: true,
        secondary_font_color: null,
        secondary_font_family: '"Arial", "Helvetica"',
        active_background_color: null,
      },
      sidecart: {
        font_size: null,
        font_color: null,
        font_family: null,
        border_color: "#f4f5f6",
        border_radius: null,
        background_color: null,
        active_font_color: null,
        active_border_color: null,
        secondary_font_size: null,
        show_product_images: true,
        secondary_font_color: null,
        secondary_font_family: null,
        active_background_color: null,
        background_color_no_items: "#f4f5f6",
      },
      auth_page: {
        font_size: null,
        font_color: null,
        font_family: null,
        border_color: "#fbf8f7",
        border_radius: null,
        background_color: null,
        tertiary_font_size: null,
        secondary_font_size: 32,
        tertiary_font_color: "#0d6cf2",
        secondary_font_color: null,
        tertiary_font_family: '"Arial", "Helvetica"',
        secondary_font_family: '"Arial", "Helvetica"',
      },
      food_hall: {
        filter_nav_text_color: "#ffffff",
        splash_screen_text_color: "#ffffff",
        filter_nav_background_color: "#333333",
        splash_screen_background_color: "#333333",
        splash_screen_background_image:
          "https://koala-marketing-api-sandbox.s3.amazonaws.com/default-assets/about-landscape.png",
      },
      locations: {
        map_key: "AIzaSyCd5G3I-6oYR8NBLTluEhZR_iH7V_U7pdY",
        map_icon: null,
        cross_street: false,
        list_display: "group",
        map_position: "right",
        delivery_search: false,
        map_icon_active: null,
        disable_locations_page: false,
      },
      android_home: {
        home_image: null,
        inbox_icon:
          "https://koala-marketing-api-sandbox.s3.amazonaws.com/default-assets/inbox-icon-2x.png",
        reorder_icon:
          "https://koala-marketing-api-sandbox.s3.amazonaws.com/default-assets/reorders-icon-2x.png",
        rewards_icon:
          "https://koala-marketing-api-sandbox.s3.amazonaws.com/default-assets/gift-icon-2x.png",
        favorites_icon:
          "https://koala-marketing-api-sandbox.s3.amazonaws.com/default-assets/heart-icon-2x.png",
        background_color: "#fbf8f7",
        header_text_color: "#222222",
        header_font_family: '"Arial", "Helvetica"',
        sub_header_text_color: "#222222",
        sub_header_font_family: '"Arial", "Helvetica"',
        badge_count_font_family: '"Arial", "Helvetica"',
        reorder_button_text_color: "#ffffff",
        selection_view_text_color: "#222222",
        sign_in_button_text_color: "#222222",
        reorder_button_font_family: '"Arial", "Helvetica"',
        selection_view_font_family: '"Arial", "Helvetica"',
        sign_in_button_font_family: '"Arial", "Helvetica"',
        order_now_button_text_color: "#ffffff",
        reorder_button_border_width: 1,
        my_account_button_text_color: "#222222",
        order_now_button_font_family: '"Arial", "Helvetica"',
        reorder_button_border_radius: 8,
        my_account_button_font_family: '"Arial", "Helvetica"',
        order_now_button_border_radius: 8,
        reorder_button_background_color: "#4a4a4a",
        order_now_button_background_color: "#0d6cf2",
      },
      integrations: {
        branch_id: null,
        userway_id: null,
        facebook_pixel: null,
        apple_itunes_app_id: null,
      },
      store_banner: {
        display: "never",
        font_size: null,
        placement: "top",
        font_color: null,
        font_family: null,
        border_color: null,
        background_color: null,
      },
      store_detail: {
        layout: "bar",
        text_color: "#003399",
        hero_height: 500,
        active_color: "#0d6cf2",
        card_position: "center",
        background_color: "#f6f6f6",
        background_image:
          "https://koala-marketing-api-sandbox.s3.amazonaws.com/fuzz-restaurant-co/assets/mango.jpeg",
        mobile_background_color: "#ffffff",
      },
      location_card: {
        font_size: null,
        font_color: null,
        font_family: null,
        border_color: null,
        border_radius: null,
        background_color: null,
        secondary_font_size: null,
        primary_button_theme: "primary",
        secondary_font_color: null,
        secondary_font_family: null,
        show_conveyance_types: false,
        secondary_button_theme: "knockout",
      },
      android_drawer: {
        separator: "#fbf8f7",
        title_font_size: 24,
        background_color: "#fbf8f7",
        title_text_color: "#222222",
        title_font_family: '"Arial", "Helvetica"',
        section_text_color: "#222222",
        section_font_family: '"Arial", "Helvetica"',
        subtitle_text_color: "#222222",
        subtitle_font_family: '"Arial", "Helvetica"',
        bottom_section_text_color: "#222222",
        bottom_section_font_family: '"Arial", "Helvetica"',
      },
      product_detail: {
        image_layout: "bleed",
        modifier_image_layout: "inline",
        pizza_option_group_layout: ["375993", "375995"],
        special_instructions_enabled: true,
        pizza_weight_option_group_layout: ["375857"],
        pizza_position_option_group_layout: ["375989"],
      },
      location_search: {
        font_size: null,
        font_color: null,
        error_color: null,
        font_family: null,
        border_color: null,
        border_radius: null,
        background_color: "#ffeeeb",
        tertiary_font_size: 20,
        secondary_font_size: 32,
        tertiary_font_color: null,
        secondary_font_color: "#222222",
        tertiary_font_family: null,
        secondary_font_family: '"Arial", "Helvetica"',
      },
      menu_categories: {
        category_nav_display: "left",
        category_nav_font_size: 16,
        category_nav_text_color: "#222222",
        category_nav_font_family: '"Arial", "Helvetica"',
        mobile_category_nav_display: "dropdown",
        category_menu_header_display: "stacked",
        category_nav_background_color: "#e9e7e7",
        category_nav_text_hover_color: "#0d6cf2",
      },
      android_features: {
        reorders: true,
        reorders_view: "CTA",
        app_rating_enabled: true,
      },
      dispatch_tracking: {
        order_origin_icon: null,
        order_tracking_icon:
          "https://koala-marketing-api-sandbox.s3.amazonaws.com/default-assets/dispatch-car-icon-2x.png",
        order_destination_icon:
          "https://koala-marketing-api-sandbox.s3.amazonaws.com/default-assets/dispatch-destination-icon-2x.png",
        dispatch_tracking_enabled: false,
      },
      menu_product_card: {
        font_size: null,
        font_color: null,
        hide_price: false,
        image_size: "cover",
        font_family: null,
        border_color: null,
        border_radius: null,
        hide_calories: false,
        background_color: null,
        hide_description: false,
        tertiary_font_size: null,
        secondary_font_size: null,
        tertiary_font_color: null,
        secondary_font_color: null,
        tertiary_font_family: null,
        secondary_font_family: '"Arial", "Helvetica"',
        hide_description_mobile: false,
      },
      order_confirmation: {
        hide_store_phone_number: false,
        order_instructions_font_size: 12,
      },
      primary_font_family: {
        bold: '"Arial", "Helvetica"',
        light: ' "Arial", "Helvetica"',
        medium: '"Arial", "Helvetica"',
        regular: '"Arial", "Helvetica"',
      },
      location_splash_page: {
        layout_align_items: "center",
        search_column_width: 450,
        location_splash_page: false,
        layout_flex_direction: "row-reverse",
        search_column_headline: "Find a location",
        image_column_background: null,
        search_results_cta_text: null,
        search_column_background: null,
        image_column_mobile_image: null,
        search_column_subheadline: null,
        container_background_image: null,
        image_column_desktop_image: null,
      },
      menu_category_header: {
        font_size: 24,
        font_color: "#222222",
        font_family: '"Arial", "Helvetica"',
        secondary_font_size: 16,
        secondary_font_color: null,
        secondary_font_family: null,
      },
      secondary_font_family: {
        bold: '"Arial", "Helvetica"',
        light: '"Arial", "Helvetica"',
        medium: '"Arial", "Helvetica"',
        regular: '"Arial", "Helvetica"',
      },
      dietary_preferences_tag: {
        font_size: null,
        font_color: null,
        font_family: null,
        border_color: null,
        border_radius: null,
        background_color: null,
        active_font_color: null,
        active_border_color: null,
        active_background_color: null,
      },
      dietary_preferences_modal: {
        font_size: null,
        font_color: null,
        font_family: null,
        border_color: null,
        border_radius: null,
        background_color: null,
        secondary_font_size: null,
        secondary_font_color: null,
        secondary_font_family: null,
      },
    },
    organization_id: 1,
  },
};
